### ISSUE TITLE
console.error: fx_pnh:

### ISSUE THREAD

**Issue by SYANiDE-** [1N3/Findsploit#1]
I get the following error twice when running the "search online" function at the end of the script on Kali 1.10, iceweasel as browser:

```
console.error: fx_pnh: 
Object
    - message = Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
    - fileName = undefined
    - lineNumber = 15
    - stack = @undefined:15:NaN|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://jid1-cz1beofm9mmlzg-at-jetpack/fx_pnh/lib/config.js:28:7|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://jid1-cz1beofm9mmlzg-at-jetpack/fx_pnh/lib/main.js:10:1|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|run@resource://gre/modules/commonjs/sdk/addon/runner.js:149:9|startup/<@resource://gre/modules/commonjs/sdk/addon/runner.js:113:7|Handler.prototype.process@resource://gre/modules/Promise-backend.js:863:11|this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:742:7|
    - toString = function () /* use strict */ toString
```

Any ideas what this could be?

Thanks,
Chase

**Comment by 1N3** [comment]
Hi, 
Not sure exactly but what happens when you just run the command 'iceweasel https://google.com &' ? 

Does it open the google homepage without error?

-1N3

**Comment by SYANiDE-** [comment]
No, actually it still appears.   To confirm, the issue does not appear to be related to Findsploit based on this discovery.  And a littlle bit of research shows that fx_pnh is related to Plug-N-Hack...  which I recall installing under a different user, while proxying a browser instance through Burp Suite or OWASP ZAP.   FWIW, running the same under the other user does not produce any error, so it appears related to Plug-N-Hack, and per-user configuration.  Please disregard, and thanks for the timely response!

**Comment by 1N3** [comment]
Hmm.. I'm on iceweasel 31.4.0. Seems like whatever is happening is possibly related to your browser specifically or perhaps some plugin installed.. 

You could try upgrading iceweasel to see if that helps (apt-get install iceweasel). Outside of this, it looks like it might be a bug in the version you're running. There's some similar errors on google when you search for the error but I can't really find anything conclusive. You can also try a different browser and update the $BROWSER_CMD setting in the script to see if that works.

**Comment by SYANiDE-** [comment]
Confirmed.  The errors were in fact related to Plug-N-Hack, which is a browser add-on that adds easy integration of security tools with the browser, such as single-click browser configuration.  This was installed for use in actually OWASP Mantra (a security testing platform based on Firefox).  Removing the browser add-on (which oddly appeared in Iceweasel) solved the issue.
likely Mantra and iceweasel were both using the same plugins base, because they're essentially both based on Mozilla/firefox.  Albeit some configuration mismatch between users' ~/.mozilla/extensions/  directories further exacerbated the per-user confusion on top of the PNH-related issues.   I'll go ahead and close this.  Thanks for your help!
