### ISSUE TITLE
Add support for OSX

### ISSUE THREAD

**Issue by mananwason** [1N3/Findsploit#12]
Right now install.sh uses apt-get to install dependencies which is not supported by OSX.

**Comment by Amar-Chaudhari** [comment]
May be create a Docker container?

**Comment by duck-nukem** [comment]
I'll try to find some time to create a Dockerfile and add it to the repo - if needed.

**Comment by duck-nukem** [comment]
An update to this - I can get it to run in a container, but the problem is with `xdg-open`, so I couldn't make it work properly. Anyone else wants to tackle the issue, feel free to ignore my attempt! 😭

**Comment by 1N3** [comment]
New version 1.9 includes text based links, so xdg-open or a browser is not necessarily needed anymore. Just copy/paste links generated in console to your browser. A little more manual, but should run fine in Docker.
