### ISSUE TITLE
Better Update Method

### ISSUE THREAD

**Issue by alexanderepstein** [1N3/Findsploit#3]
If you utilize GitHub releases it is possible to implement a simpler update process. Inside of the findsploit bashfile allow the use of an option something like -u which will query the GitHub api for the latest release tag. 

Then compare this release version to the current version if the latest release is greater then, it should ask the user if they want to update. If they say yes it can clone the repository to a temp directory, git checkout to the newsest stable release, run your install script and then remove the temperary directory. 

I did something similar for a bash script I wrote. I looked into your code and it seems like it shouldn't be to bad to implement since you don't seem to use the bash options at all so it wouldn't change old functionality.

If im not making sense I'd love to explain further or possibly implement a version of it into your code.

**Comment by 1N3** [comment]
I like the idea and will implement it but do you have details for how to query the Github API for the latest release version? If you want to send a pull request with the changes, that works too.

**Comment by alexanderepstein** [comment]
##### Set this at the top of the file and change it with every new release
```bash
currentVersion=1.5
```
##### This is the code that would go under the Findsploit -u option which I can show you how to setup later. I modified this from my own code, it seems you use egrep where I use perl grep I'm not sure how that will affect the functionality. I can look into a further solid implementation later today or tomorrow and will create a pull request. 

```bash
   if [[ $(curl -s https://api.github.com/repos/1N3/Findsploit/tags) == "" ]];then
    echo "Error: no active internet connection"
    exit 1
  fi
  latestVersion=$(curl -s https://api.github.com/repos/1N3/Findsploit/tags | grep -Po '"name":.*?[^\\]",'| head -1 | cut -c11-13)
  if [[ "$latestVersion" != "$currentVersion"  && "$latestVersion" != "" ]]; then
    echo "Version $latestVersion available"
    echo -n "Do you wish to update Findsploit [Y/n]: "
    read answer
  if [[ "$answer" == "Y" || "$answer" == "y" ]] ;then
  cd  ~ || { echo 'Update Failed' ; exit 1 ; }
rm -r Findsploit  2> /dev/null
git clone https://github.com/1N3/Findsploit || {echo "Couldn't download latest version" ; exit 1; }
cd Findsploit ||  { echo 'Update Failed' ; exit 1 ;}
git checkout $latestVersion 2> /dev/null
#chmod +x install.sh #this might be necessary in your case but wasnt in mine.
./install.sh
cd .. 
rm -r Findsploit
  else
      exit 1
  fi

else
  echo "Findsploit is already the latest version"
fi
```  

If you are going to add options, a -v option is also nice it essentially just echos the current version variable which my method requires you to set at the top of the bash file anyways
`echo "Findsploit Version $currentVersion"`

**Comment by 1N3** [comment]
Thanks for the assist! This is implemented in v1.5a.

**Comment by alexanderepstein** [comment]
Seems like you implemented it well, just know that the cut command when checking the GitHub api for the latest version is not going to recognize that the latest version is 1.5a it will only recognize [a-Z || 0-9].[a-Z || 0-9]  Therefore currently the program will set the latest_version variable for the  1.5a release as 1.5 so it will believe you are on the latest version

**Comment by 1N3** [comment]
ah, good catch man! Thanks for the pull request.

**Comment by alexanderepstein** [comment]
Glad to help
