### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mboelen** [1N3/Findsploit#6]
Under what license is this software available? We want to cover the tool, but can't find it.

Thanks!

**Comment by 1N3** [comment]
Thanks for your interest. This software is free to use, distribute and modify as desired as long as original credit is maintained to the author (1N3@CrowdShield). 

Let me know if you plan on including this somewhere so I can reference and help get the word out. 👍

**Comment by mboelen** [comment]
Sure,  here is the direct link: https://linuxsecurity.expert/tools/findsploit/
Our goal: as authors of tools ourselves, we want to cover Linux security tools and display the what/how/why behind them and promote them. Not only do we want to promote the tool, but also the people behind the project.

In this case, a license file would be great, reducing one of the 'negatives' very easily :)

Regarding your real name: I don't think it is that secret after a bit of Googling, but looks like you have the preference to stay behind an alias? Otherwise, it would be our honor to put a real name to the tool and create a related profile with your work.

In case anything is sensitive, or you have a preference you want to share in private, send me a DM on Twitter, or email to firstname.lastname at cisofy.com

**Comment by 1N3** [comment]
Awesome. Thanks for including the project.  

I created a license file under the main branch for reference.

I would prefer to use my alias 1N3@CrowdShield as most of my work is linked to my alias already if that works. 

If there's any interest in some of my other repo's, definitely let me know!

**Comment by mboelen** [comment]
You are welcome. And thanks, I've updated the project page.

Yes, we definitely want to cover your other work (some are already queued for review). We want to link to real names, so people can learn more about the author (e.g. see their LinkedIn, GitHub, or social media profiles). For example, have a look at my profile: https://linuxsecurity.expert/p/michael-boelen

We are totally fine if some projects do not display the author's name, yet we will mark that as a possible downside. Reasons include that it may be harder to reach out and limits networking opportunities, the trust level may be lower not seeing who is behind the software.

Although we don't create profiles for aliases, we already include their alias in the database. In the near future, we will extend the profiles: show this alias, add interviews, and display company history. Directly and indirectly, we want to promote the work of authors and even the company he/she is working for. After all, you are doing great work and we want to display that.

Hope that gives an insight on the "real name" thing :)

**Comment by 1N3** [comment]
Awesome! Sounds good!
